---
nav:
    - Home: index.md
    - Get Started:
          - Quick Start:
                - learn/quick-start.md
                - "Tutorial: Tic-Tac-Toe ğŸš§" : learn/tutorial-tic-tac-toe.md
                - Thinking in React : learn/thinking-in-react.md
          - Installation:
                - learn/installation.md
                - Start a New React Project : learn/start-a-new-react-project.md
                - Add React to an Existing Project ğŸš« : learn/add-react-to-an-existing-project.md
                - Editor Setup ğŸš§ : learn/editor-setup.md
                - React Developer Tools ğŸš« : learn/react-developer-tools.md
          - More Tutorials:
                - "Tutorial: React Bootstrap ğŸš«" : learn/tutorial-react-bootstrap.md
                - "Tutorial: Material UI ğŸš«" : learn/tutorial-material-ui.md
    - Learn React:
          - Describing the UI:
                - Your First Component ğŸš§ : learn/your-first-component.md
                - Importing and Exporting Components ğŸš§ : learn/importing-and-exporting-components.md
                - Writing Markup with PSX ğŸš« : learn/writing-markup-with-psx.md
                - Python in PSX with Curly Braces ğŸš« : learn/python-in-psx-with-curly-braces.md
                - Passing Props to a Component ğŸš§ : learn/passing-props-to-a-component.md
                - Conditional Rendering ğŸš§ : learn/conditional-rendering.md
                - Rendering Lists ğŸš§ : learn/rendering-lists.md
                - Keeping Components Pure ğŸš§ : learn/keeping-components-pure.md
          - Adding Interactivity:
                - Responding to Events ğŸš§ : learn/responding-to-events.md
                - "State: A Component's Memory ğŸš§" : learn/state-a-components-memory.md
                - Render and Commit ğŸš§ : learn/render-and-commit.md
                - State as a Snapshot ğŸš§ : learn/state-as-a-snapshot.md
                - Queueing a Series of State Updates ğŸš§ : learn/queueing-a-series-of-state-updates.md
                - Updating Objects in State ğŸš§ : learn/updating-objects-in-state.md
                - Updating Arrays in State ğŸš§ : learn/updating-arrays-in-state.md
          - Managing State:
                - Reacting to Input with State ğŸš§ : learn/reacting-to-input-with-state.md
                - Choosing the State Structure ğŸš§ : learn/choosing-the-state-structure.md
                - Sharing State Between Components ğŸš§ : learn/sharing-state-between-components.md
                - Preserving and Resetting State ğŸš§ : learn/preserving-and-resetting-state.md
                - Extracting State Logic into a Reducer ğŸš§ : learn/extracting-state-logic-into-a-reducer.md
                - Passing Data Deeply with Context ğŸš§ : learn/passing-data-deeply-with-context.md
                - Scaling Up with Reducer and Context ğŸš§ : learn/scaling-up-with-reducer-and-context.md
          - Escape Hatches:
                - Referencing Values with Refs ğŸš§ : learn/referencing-values-with-refs.md
                - Manipulating the DOM with Refs ğŸš§ : learn/manipulating-the-dom-with-refs.md
                - Synchronizing with Effects ğŸš§ : learn/synchronizing-with-effects.md
                - You Might Not Need an Effect ğŸš§ : learn/you-might-not-need-an-effect.md
                - Lifecycle of Reactive Effects ğŸš§ : learn/lifecycle-of-reactive-effects.md
                - Separating Events from Effects ğŸš§ : learn/separating-events-from-effects.md
                - Removing Effect Dependencies ğŸš§ : learn/removing-effect-dependencies.md
                - Reusing Logic with Custom Hooks ğŸš§ : learn/reusing-logic-with-custom-hooks.md
                - Communicating Data Between Server and Client ğŸš§ : learn/communicate-data-between-server-and-client.md
                - Convert Between VDOM and HTML ğŸš§ : learn/convert-between-vdom-and-html.md
                - VDOM Mutations ğŸš§ : learn/vdom-mutations.md
                - Creating VDOM Event Handlers ğŸš§ : learn/creating-vdom-event-handlers.md
                - Creating HTML Tags ğŸš§ : learn/creating-html-tags.md
                - Creating Backends ğŸš§ : learn/creating-backends.md
                - Manually Register a Client ğŸš§ : learn/manually-register-a-client.md
    - Reference:
          - Hooks:
                - Use State ğŸš§ : reference/use-state.md
                - Use Effect ğŸš§ : reference/use-effect.md
                - Use Context ğŸš§ : reference/use-context.md
                - Use Reducer ğŸš§ : reference/use-reducer.md
                - Use Callback ğŸš§ : reference/use-callback.md
                - Use Memo ğŸš§ : reference/use-memo.md
                - Use Ref ğŸš§ : reference/use-ref.md
                - Use Debug Value ğŸš§ : reference/use-debug-value.md
                - Use Connection ğŸš§ : reference/use-connection.md
                - Use Scope ğŸš§ : reference/use-scope.md
                - Use Location ğŸš§ : reference/use-location.md
                - Use ID ğŸš« : reference/use-id.md
                - Use Deferred Value ğŸš« : reference/use-deferred-value.md
                - Use Imperative Handle ğŸš« : reference/use-imperative-handle.md
                - Use Insertion Effect ğŸš« : reference/use-insertion-effect.md
                - Use Layout Effect ğŸš« : reference/use-layout-effect.md
                - Use Sync External Store ğŸš« : reference/use-sync-external-store.md
                - Use Transition ğŸš« : reference/use-transition.md
          - HTML Tags:
                - Common Props ğŸš§ : reference/common-props.md
                - Usage ğŸš§ : reference/usage.md
          - Backends:
                - FastAPI ğŸš§ : reference/fastapi.md
                - Flask ğŸš§ : reference/flask.md
                - Sanic ğŸš§ : reference/sanic.md
                - Starlette ğŸš§ : reference/starlette.md
                - Tornado ğŸš§ : reference/tornado.md
                - Django ğŸš§ : reference/django.md
                - Jupyter ğŸš§ : reference/jupyter.md
                - Plotly Dash ğŸš§ : reference/plotly-dash.md
          - Protocol Structure ğŸš§ : reference/protocol-structure.md
          - Client API ğŸš§ : reference/client-api.md
    - About ReactPy:
          - Changelog ğŸš§ : about/changelog.md
          - Community ğŸš§ : about/community.md
          - Running Tests ğŸš§ : about/running-tests.md
          - Contributing Code ğŸš§ : about/code.md
          - Contributing Documentation ğŸš§ : about/docs.md

theme:
    name: material
    custom_dir: docs/overrides
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/white-balance-sunny
              name: Switch to light mode
          primary: light blue
          accent: light blue
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
          primary: black
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - content.code.copy
    icon:
        repo: fontawesome/brands/github
    logo: https://raw.githubusercontent.com/reactive-python/reactpy/main/branding/svg/reactpy-logo-square.svg
    favicon: https://raw.githubusercontent.com/reactive-python/reactpy/main/branding/svg/reactpy-logo-square.svg

markdown_extensions:
    - toc:
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.highlight:
          linenums: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.inlinehilite
    - admonition
    - attr_list
    - md_in_html

plugins:
    - search
    - include-markdown
    - section-index
    # - git-authors
    # - minify:
    #       minify_html: true
    #       minify_js: true
    #       minify_css: true
    #       cache_safe: true
    # - git-revision-date-localized:
    #       fallback_to_build_date: true
    # - spellcheck:
    #       known_words: dictionary.txt
    #       allow_unicode: no
    #       ignore_code: yes

extra:
    generator: false

extra_javascript:
    - static/js/extra.js

extra_css:
    - static/css/extra.css

watch:
    - docs
    - mkdocs.yml
    - README.md
    - CHANGELOG.md

site_name: ReactPy
site_author: Archmonger
site_description: It's React, but in Python.
copyright: Copyright &copy; 2023 Reactive Python
repo_url: https://github.com/reactive-python/reactpy
site_url: https://reactive-python.github.io/reactpy
repo_name: reactive-python/reactpy
edit_uri: edit/main/docs/src
docs_dir: docs/src
