name: Nox Session

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      nox-args:
        required: true
        type: string
      nox-env:
        required: false
        type: string
        default: "{}"
      nox-session-args:
        required: false
        type: string
      runs-on-array:
        required: false
        type: string
        default: '["ubuntu-latest"]'
      python-version-array:
        required: false
        type: string
        default: '["3.x"]'

jobs:
  nox-session:
    name: ${{ format(inputs.job-name, matrix.python-version, matrix.runs-on) }}
    strategy:
      matrix:
        runs-on: ${{fromJson(inputs.runs-on-array)}}
        python-version: ${{fromJson(inputs.python-version-array)}}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: pip install -r requirements/nox-deps.txt
      - name: Run Sessions
        env: ${{ inputs.nox-env }}
        run: nox ${{ inputs.nox-args }} --stop-on-first-error -- ${{ inputs.session-args }}
