name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  python-exhaustive:
    uses: ./.github/workflows/.nox-session.yml
    with:
      job-name: "python-{0}"
      nox-args: "-t check-python"
      session-args: "--pytest --maxfail=3"
  python-environments:
    uses: ./.github/workflows/.nox-session.yml
    with:
      nox-args: "-s check-pytest-tests"
      session-args: "--skip-coverage --pytest --maxfail=3"
      runs-on-array: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-version-array: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
  docs:
    uses: ./.github/workflows/.nox-session.yml
    with:
      job-name: "python-{0}"
      nox-args: "-s check-docs"
  javascript:
    uses: ./.github/workflows/.nox-session.yml
    with:
      job-name: "{1}"
      nox-args: "-t check-javascrcipt"
